### ISSUE TITLE
Blue Iris nstall instructions - missing apps?

### ISSUE THREAD

**Issue by whasf** [flyjmz/jmzSmartThings#5]
First step of your install instructions, I've added your GitHub and I am not seeing all four items I am supposed to import. I think I found two of them. See attached screenshot.

![github capture](https://user-images.githubusercontent.com/6373706/67060335-dfa72a00-f121-11e9-99d4-1c8db2f2f1ea.PNG)

**Comment by flyjmz** [comment]
The other two are device handlers, so you have to go the device handler
page and then install from repository, just as your screenshot shows for
the smartapps page. Sorry, that is t clear at all in the instructions!

Good luck with setting it all up. Let me know if I can help more.

**Comment by flyjmz** [comment]
I assume you found them, closing this out.
