### ISSUE TITLE
Unable to clone this repository in Windows due to invalid file name

### ISSUE THREAD

**Issue by Idan37S** [flyjmz/jmzSmartThings#8]
Hi,

Can you please change the file name of "jmzSmartThings/smartapps/flyjmz/blue-iris-fusion.src/HTTPS:SSL:STUNNEL How-To.md" so it wouldn't contain ':' character?

This file name isn't valid in Windows and makes it not possible to clone this repo.

Thanks.

**Comment by flyjmz** [comment]
Done
